Готова первая проектная работа
Mixail999/s-chistogo-lista pull request #2
Opened 2024-02-15 19:21 UTC by Mixail999

Отправляю на ревью

2024-02-16 13:08 UTC, Avaakum requested changes
Развернуть общий комментарий ⬇︎

Доброго времени суток. У вас получилась хорошая работа!

_Что понравилось:_

- Хорошая структура HTML
- похоже на макет
- Хорошее форматирование документа
- хорошие стили
- используется семантика
- Используются списки


_Что необходимо исправить:_

- **Все комментарии, кроме комментариев «Можно лучше» и «Отлично»**

- https://disk.yandex.ru/i/B-zYHjnYhd5tfA Нужно указать альтернативный шрифт (тип засечек для выбора шрифта браузера без засечек умолчанию (для шрифта Inter)значение sans-serif и для шрифта с засечками(EB Garamond) тип serif) для каждого значения font-family в проекте, кроме файла подключения шрифтов, где это св-во задаёт только название подключаемого шрифта
    - https://doka.guide/css/font-family


- при ширине больше чем в макете контент должен быть или растянут или по центру страницы


- Несоответствия макету:
    - https://disk.yandex.ru/i/e8slM_zAfO1GZQ высота строки
    - https://disk.yandex.ru/i/HmuKttY8qq_4SQ отступ над футером, высота строки в тексте
    - https://disk.yandex.ru/i/a1NK0qF7zEpFVA выравнивание ссылок




_Что можно улучшить:_

- Все комментарии "Можно лучше"

- Селекторы в файле стилей должны располагаться в порядке их появления в html

- В любом месте в файлах CSS в проекте(кроме самого CSS файла подключения шрифтов, где указывается только название подключаемого шрифта), где указано свойство  `font-family`  помимо основного шрифта так же должен быть указан альтернативный шрифт и тип засечек. Это делается для того, что если по каким-то причинами основной шрифт не загрузится, то внешний вид страницы не будет изменен очень сильно.  Порядок написания шрифтов: Основной шрифт, [Веб-безопасный альтернативный шрифт(по ссылке список этих шрифтов)](https://www.cssfontstack.com/), Тип засечек. Пример ` font-family: Inter, Arial, sans-serif; ` 

- Желательно использовать все классы по БЭМ. 
  - https://ru.bem.info/methodology/quick-start/
  - Проверить ошибки БЭМ можно на  https://nglazov.github.io/bem-validator-page/
  - Структуру можно проверить на https://yoksel.github.io/html-tree/

- Можно использовать атрибуты `target="_blank"` для ссылок на сторонние ресурсы для того чтобы пользователю не приходилось заново открывать сайт проекта
- Для более точной корректировки размеров текстов и расстояний между элементами можно воспользоваться [расширением PixelPerfect](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi) для Chrome 


**Напоминание:** После выполнения всех критических замечаний работа будет принята. Предложения по улучшению выполняются по желанию.

Желаю успеха!

2024-02-16 13:08 UTC, Avaakum commented on index.html
> +                <nav>
Лишняя семантика, тут нет списка ссылок

2024-02-16 13:08 UTC, Avaakum commented on index.html
> +                <nav>
Лишняя семантика, тут нет списка ссылок

2024-02-16 13:08 UTC, Avaakum commented on index.html
> +                            <p class="card__title">Начать любыми словами</p>
Это должен быть заголовок. Для этого  и следующих заголовков используйте h4 по структуре


---


- Про заголовки и подзаголовки на примере другой страницы с секциями, хэдером, и футером: у нас есть **один заголовок h1 на странице**, в каждой секции есть свой заголовок h2, если там есть другие элементы с заголовками ниже по иерархии, то они будут h3. Если например в секции был бы заголовок h2 и подзаголовок h3, то элементы с заголовками ниже по иерархии в этой же секции были бы уже h4.

2024-02-16 13:08 UTC, Avaakum commented on index.html
> +            <p class="footer__links"><a class="links" href="#0">ВК</a> <a class="links" href="#0">Ютуб</a></p>
` footer__links `   это не параграф, а контейнер для двух ссылок, можно использовать див



---

**Можно лучше:**




Можно использовать для обертки списка ссылок тег `<nav>`, можно даже без класса, только для семантики(А внутри будет ul и li и внутри ссылки)
Этим элементом принято выделять список из ссылок, отвечающий за навигацию по сайту и не только. Добавление этого элемента улучшает восприятие вашей верстки поисковыми машинами, а так же скринридерами. 
Можно использовать несколько тегов `nav` в проекте.

https://doka.guide/html/nav/#alyona-batickaya-sovetuet

2024-02-16 13:08 UTC, Avaakum commented on styles/style.css
> +.bunin {
У первой и третьей карточки одинаковые стили, различается только контент html, используйте общий класс, что бы стили не дублировались

2024-02-17 19:27 UTC, Avaakum requested changes
Развернуть общий комментарий ⬇︎

Здравствуйте. К сожалению проект отклоняется от проверки. Итерация не теряется. 





- _На повторных итерациях не исправлены критические замечания._ 
    - **Пример:** 
              - Начиная с неисправленных пунктов в общем комментарии https://disk.yandex.ru/i/4PgywCa8JuSmbg  , в коде: https://disk.yandex.ru/i/STTaDo3WalrrXw  в ревью предыдущей итерации нужно проверить исправление **всех критических комментариев** в работе. Если у вас есть сомнения по поводу того, что комментарий исправлен, то пожалуйста, перечитайте комментарии внимательно, там описано, что нужно исправить в работе. Если что-то исправить не получается, то можно смело обращаться к наставнику, он сможет подсказать. Чтобы исправить ошибки валидатора(при наличии), можно в chrome перевести страницу на русский, чтобы было понятнее, что именно за ошибки он выдаёт. А для соответствия макету можно воспользоваться [расширением PixelPerfect](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi  )  для Chrome.



     - Пожалуйста, будьте внимательны, проверяйте, исправляйте и присылайте работу только после исправления **всех критических замечаний** c предыдущей итерации
    - Если у вас есть технические проблемы, то попробуйте обратиться в поддержку или спросить в чате студентов не было ли у кого похожих случаев.

2024-02-20 19:04 UTC, Mixail999 commented
> Отправляю на ревью(попытка 2)

2024-02-20 19:06 UTC, Mixail999 commented
Готова первая проектная работа

2024-02-21 12:54 UTC, Avaakum approved these changes
Развернуть общий комментарий ⬇︎

Здравствуйте! Рад вам сообщить, что ваша работа принята. Желаю вам удачи в следующих спринтах и проектах! 

---

_Что необходимо исправить:_

- Комментарии в коде

- https://disk.yandex.ru/i/-952Bndwc0ocBA Нужно указать альтернативный шрифт (тип засечек для выбора шрифта браузера без засечек по-умолчанию (для шрифта Inter)значение sans-serif и для шрифта с засечками(EB Garamond) тип serif) **для каждого значения font-family в проекте, кроме файла подключения шрифтов**, где это св-во задаёт только название подключаемого шрифта
    - https://doka.guide/css/font-family

---




Ссылки:

- Можно использовать неразрывные пробелы для того чтобы текст не переносился в неожиданных местах. Неразрывные пробелы заменяют обычные, если нужно чтобы какая-то фраза не переносилась, например не нужно чтобы "на собаках" раскидывалось по разным строчкам при некоторых ширинах экранов, тогда `«на&nbsp;собаках»`. Но если страница с адаптацией, то всегда стоит проверять как текст с пробелами выглядит на всех ширинах.
- Про альтернативный текст для картинок https://habr.com/ru/post/341810/
- [Ссылка про подгрузку шрифтов](https://only-to-top.ru/blog/tools/2019-03-13-nastrojte-pokaz-vsego-teksta-vo-vremya-zagruzki-veb-shriftov.html) 


Несколько  ссылок на материал по теме нативных CSS переменных от авторов практикума:

- [1 часть](https://tproger.ru/articles/custom-properties-in-css-part-1/)

- [2 часть](https://tproger.ru/articles/custom-properties-in-css-part-2/)

- [3 часть](https://tproger.ru/articles/custom-properties-in-css-part-3/)

2024-02-21 12:54 UTC, Avaakum commented on fonts/chernovik
> +/* footer */
Лишний файл

2024-02-21 12:54 UTC, Avaakum commented on styles/style.css
> +    padding: 40px 20px 40px 20px;
Для соответствия макету нижний отступ (3е значение) сделайте 60px

https://doka.guide/css/margin/

2024-02-21 12:54 UTC, Avaakum commented on styles/style.css
> +    line-height: 22px;
Для соответствия макету используйте значение 21.5px для высоты строки

2024-02-21 12:54 UTC, Avaakum commented on styles/style.css
> +    height: 22px;
**Высоту для текста нужно удалить**

---

 В случае, если элемент, содержащий, например, текстовый контент ограничить по высоте - теряется масштабируемость. При редактировании (Добавлении/удалении символов) - нарушается визуальное отображение верстки, она начинает "ломаться". Старайтесь избегать фиксированных значений для ```height;`

2024-02-21 12:54 UTC, Avaakum commented on styles/style.css
> +    width: 101px;
Фиксированное значение для текстовых элементов чревато некорректным отображением и усложнением кода. 
Особенно много неприятностей это добавит при создании верстки, адаптирующейся под различные экраны устройств. Фиксированные значение ширины приводят к тому, что вне зависимости от текстово содержимого и устройства просмотра - ширина будет равна только установленному в свойстве `width` значению. 

CSS предлагает более мягкое свойство - `max-width`. Старайтесь использовать его для текстовых элементов. Чтобы не потерять отображение верстки при небольшом количестве текста внутри элемента - используйте связку `max-width` и `width:100%`.

---

Используйте св-во max-width практически для любого текстового элемента, за исключением тех мест, где он специльно должен быть всегда одной ширины даже при меньшем тексте

2024-02-21 12:54 UTC, Avaakum commented on index.html
> +                        <h3 class="card__author-name">Алексей Поляринов</h3>
Это не заголовок, используйте тег p

2024-02-21 12:54 UTC, Avaakum commented on index.html
> +                        <h3 class="card__author-name">Иван Бунин</h3>
Это не заголовок, используйте тег p

2024-02-21 12:54 UTC, Avaakum commented on index.html
> +                        <h4 class="card__title">Начать любыми словами</h4>
- Уровень заголовка не соответствует структуре страницы. Тут  будет h3 по структуре

2024-02-21 12:54 UTC, Avaakum commented on index.html
> +                        <h4 class="card__title">Сделать из задачи рутину</h4>
- Уровень заголовка не соответствует структуре страницы. Тут  будет h3 по структуре

2024-02-21 12:54 UTC, Avaakum commented on index.html
> +                        <p class="card__title__bright">Поставить перед собой рамку для фотографии</p>
Это должен быть заголовок

Тут  будет h3 по структуре

2024-02-23 16:04 UTC, merged